### PR TITLE
Content reset

### PR DESCRIPTION
**Pull request by chakhdin**
Modifications to strings.xml and settings.xml somehow got lost. The option to clear the downloaded files was not visible in the settings

### CODE REVIEW

**Comment by chakhdin** [comment]
Wait up a bit on this one. I somehow lost all the changes and this fix is not complete.
Sorry

**Comment by Diblo** [comment]
Do a URL and then a Base64 decoding: `aGVucmlrKGF0KWRpYmxvKGRvdClkaw%3D%3D` ... :+1:

**Comment by Diblo** [comment]
:+1:

**Comment by chakhdin** [comment]
@Diblo, This feature should be ok now.
I only can test on windows x64. So if you can test on any other platform it would be useful.
This uses shutil to remove, which should work on Unix/Mac OS as well. Not sure about Android though

**Pull request merged**
