### PR TITLE
Polish language file

### PR DESCRIPTION
**Pull request by majki09**
my first

### CODE REVIEW

**Comment by Diblo** [comment]
Hi @majki09 
Thanks for the translation. There are a few things you should do.
You must create a folder named "Polish" in the "language" folder, and move the file "strings.xml" to the "Polish" folder.
I also need you to translate "summary" and "description" in the file "addon.xml". The "addon.xml" file is located in the folder "plugin.video.kodipopcorntime" and your ISO language code is '`lang="pl"`'.

Many thanks in advance :+1:

**Comment by majki09** [comment]
Hi @Diblo 
Thanks for your reply. Yes, I know that my translation file should be in proper folder, but I don't know how to create a new folder. Maybe I don't have some permission? Can you please show me how to do it? This is my first activity at github.com. This is because I'm excited by KODI Popcorn Time and I feel the need for translation. I'm sure there will be more excited Polish users :)

I've added strings in addon.xml file just as you described. Can you see it? Or do I have to do something more?

Thanks for your patience, I'm new here

**Comment by Diblo** [comment]
Download and install [GitHub Desktop](https://desktop.github.com/) from GitHub

**Comment by Diblo** [comment]
I do not see that you have made changes in addon.xml on your repo. However install [GitHub Desktop](https://desktop.github.com/) and make the changes. We take the rest afterwards :+1:

**Comment by majki09** [comment]
Hey, I moved my strings.xml file to Polish folder and changed addon.xml
Is everything OK now?

Thanks, majki09

**Comment by Diblo** [comment]
Nice job :+1:

**Comment by Diblo** [comment]
I understand that you already want to use this language?

**Comment by majki09** [comment]
Yes, I want to check my translation using it in KODI Popcorn Time. This is needed because some polish words has multiple meanings and I want to ensure that the translated sentences and captions makes sense. Should I wait for the new release?

**Comment by Diblo** [comment]
Hi @majki09 
Sry for the waiting time.
I have work hard on Alpha version 2 so you could get this more complete version instead of Alpha version 1. You can download it [her](https://github.com/Diblo/KODI-Popcorn-Time/wiki/Test-releases#test-alpha-version-070)

\- Remember to read the note :+1: 
Diblo

**Comment by majki09** [comment]
Hey @Diblo 
Thanks for info. I've made some corrections in my translation. I've seen that some strings were replaced, but it's OK now.

Also I tried out your 0.7 alpha. It's much better than previous version. But when I try to load any movie I'm getting "Torrent error". I installed an addon from alpha2 zip.

Regards,
majki09

**Comment by Diblo** [comment]
We have correct playback errors in the last hour. You should therefore redownload and install the addon. But I do not think that is the problem. So if it continues then go to the the addon settings and turn on debugging. Then reproduce the error and create a new one insult with the log file.

See also [Easy Log file guide.](http://kodi.wiki/view/Log_file/Easy) and

kodi_popcorn_time_-_settings_advanced_1 1

**Comment by majki09** [comment]
Thanks for the info. I followed your instruction and added a comment in issues
https://github.com/Diblo/KODI-Popcorn-Time/issues/54#issuecomment-144453523

**Pull request merged**
