### PR TITLE
Cache reset

### PR DESCRIPTION
**Pull request by chakhdin**
Fix cache reset from add-on settings #34

### CODE REVIEW

**Comment by Diblo** [comment]
NOTE: This does not resolve the entire problem with insults https://github.com/Diblo/KODI-Popcorn-Time/issues/10 and https://github.com/Diblo/KODI-Popcorn-Time/issues/34.
1. The first problem is that the folder must be cleared of all files and folders except the folder ".storage".
2. Another problem is that the user can select a download path (in settings), pointing to a system partition without know it. In this way, the error will still be present. Therefore, it is only half a solution.


However, I will merge the pull request, if you solve the first problem :) And leave it as half solved :+1:

**Comment by chakhdin** [comment]
#34 only mentions resetting cache. The second part is in #10, which I don't mention at all. I believe you linked the two issues by error. 
Regarding the users using a small and/or system partition as download directory, maybe you should force the users to select a folder before he or she can use the plugin. Doing so the user will have to choose a directory and will be aware of the storage impact.

**Comment by Diblo** [comment]
Oh yes. I have linked the two insults together because the root of the problem is the same.

The issue #34 describes a problem with running out of space. The reason for this is the http2torrent unexpected shuts down (for unknown reason), and therefore can not clear the allocated space. The problem is that http2torrent create allocated space based on file names. (HIGH RISK: The operating systems runs out of space and shuts down, when the various allocated files are not deleted)

The issue #10 describes a problem with running out of space. The reasons is because the operating systems runs out of space and shuts down, because there is no space for the allocated file. This is a problem for http2torrent as it unexpected shuts down. The problem is that http2torrent do not delete old allocated space after it has been unexpected shuts down.

I therefore see these two insults as uniform as both problems arise when http2torrent unexpected shuts down. This lead to an unexpected excess allocated space that cause problems.

If we look at this problem in relation to allow users to choose a download path. The same problems occur and all the contents of the folder can not simply be erased.

**Comment by chakhdin** [comment]
I don't want to be contentious, but #34 says "Some plugin functionality breaks permanently if the listing cache files become corrupted..... What fixed the problem:

re-installing the program after manually deleting the ...AppData\Roaming\Kodi\userdata\addon_data\plugin.video.kodipopcorntime folder
It would be useful if there was an option somewhere in the plugin interface to do this. "

#34 is about cleaning the cache, not running out of space, though it was what actually broke the plugin. #34 is not a copy of #10, it's a different request. So I'd unlink the two issues. 
Anyway, let's not waste time on this. I'm open to help you on the plugin a part from fixing and polishing. Is there anything I can do?

**Comment by Diblo** [comment]
You are right.
I need you to correct Clean Cache function to also remove all subfolders with content but you may not remove the subfolder ".storage", only it's content.
And if you got the time, you may solve insult #10. - I imagine a function that can determine whether there is the necessary space. You can also help with solving unexpected debris from the allocated space. - I imagine a way to remember the last allocated space, but i am not sure that it can be done at this way.

**Pull request merged**
