### PR TITLE
Added Dutch translation file

### PR DESCRIPTION
**Pull request by JKetelaar**
Added Dutch translation file for this add-on.
Two others reviewed this file and everything should be translated correctly now.

### CODE REVIEW

**Comment by Diblo** [comment]
Thanks :+1: :)

**Comment by Diblo** [comment]
Can you translate the addon description https://github.com/Diblo/KODI-Popcorn-Time/blob/master/plugin.video.kodipopcorntime/addon.xml

**Comment by JKetelaar** [comment]
Done
https://github.com/Diblo/KODI-Popcorn-Time/pull/26

**Comment by JKetelaar** [comment]
Oh and it's not German but Dutch

**Pull request merged**
